name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.5.7, 2.6.6, 2.7.2]

    container:
      image: ruby:${{ matrix.ruby-version }}

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: |
          bundle exec rake test
